### ISSUE TITLE
Add information on Homepage

### ISSUE THREAD

**Issue by Raunaksingh100** [cggvuhh/My-online-meal.com#2]
### Description-
Add more information on homepage see in the screenshot given below for the better understanding

### screenshot-
![now](https://user-images.githubusercontent.com/65535360/94368613-a3869280-0102-11eb-9913-2e743fea3337.PNG)

**Comment by cggvuhh** [comment]
@Raunaksingh100 i will fixed

**Comment by gudianirudha** [comment]
I want to work on this!

**Comment by Raunaksingh100** [comment]
> I want to work on this!

Go ahead !!!

**Comment by gudianirudha** [comment]
done !

**Comment by sakshi006** [comment]
Hey!
Can i work on this?

**Comment by Raunaksingh100** [comment]
> done !

Plz link your pr in this issue

**Comment by Raunaksingh100** [comment]
> Hey!
> Can i work on this?
> 

Sorry it already fixed
