### ISSUE TITLE
change the colour of the button

### ISSUE THREAD

**Issue by cggvuhh** [cggvuhh/My-online-meal.com#29]
### descption--
change the colour of thebutton ""red to black"" see in the screenshot given below--

### screenshot--
![image_2020-10-03_131138](https://user-images.githubusercontent.com/68186540/94986151-fa182480-0579-11eb-967f-b9b3df5db3cd.png)

**Comment by Raunaksingh100** [comment]
i will fixed

**Comment by cggvuhh** [comment]
go ahead!!!

**Comment by akshitkumar450** [comment]
i want to contribute ..
