### ISSUE TITLE
Heading is overlapping to home

### ISSUE THREAD

**Issue by cggvuhh** [cggvuhh/My-online-meal.com#3]
### Description--
The heading "Our services"" is overlapping to the homepage image see in the screenshot for the better understanding

### screenshot --
![b](https://user-images.githubusercontent.com/68186540/94564168-4830dd80-0285-11eb-876b-b7a3f6c7f648.PNG)

**Comment by Raunaksingh100** [comment]
can i work on this issue??

**Comment by cggvuhh** [comment]
@Raunaksingh100  go ahead!!!
