### ISSUE TITLE
Need placeholder in box

### ISSUE THREAD

**Issue by cggvuhh** [cggvuhh/My-online-meal.com#4]
### Description--
Add the placeholder in the message box add the given below line in the message box also see in the screenshot given below for the better understanding
~ ""Enter your message here"" add this line.....

### screenshot--
![1](https://user-images.githubusercontent.com/68186540/94566010-829b7a00-0287-11eb-8edc-acc8f48fa7df.PNG)

**Comment by Raunaksingh100** [comment]
can i work on this issue??

**Comment by cggvuhh** [comment]
@Raunaksingh100 go ahead!!

**Comment by Avninder99** [comment]
can i also try ?

**Comment by cggvuhh** [comment]
> can i also try ?

NO it lead to duplicate work

**Comment by Raunaksingh100** [comment]
can you assign me this issue
