### ISSUE TITLE
Change the UI of footer 

### ISSUE THREAD

**Issue by cggvuhh** [cggvuhh/My-online-meal.com#5]
### Description--
The colour of the footer is need to be changed-
~ first changed the colour of the footer Black to red. 

### screenshot--
![3](https://user-images.githubusercontent.com/68186540/94566970-972c4200-0288-11eb-8df0-f88934d4e677.PNG)

**Comment by SaiKiranRebba** [comment]
hi @cggvuhh . I can do this. Send me the details

**Comment by cggvuhh** [comment]
@SaiKiranRebba read pr description

**Comment by Raunaksingh100** [comment]
@SaiKiranRebba just changed the Black footer to red

**Comment by SaiKiranRebba** [comment]
Sure i can change the footer color to red

**Comment by al-habibi-1107** [comment]
Sure i could give it an all around space to make the footer distinctive , and some font modifications

**Comment by Raunaksingh100** [comment]
> Sure i could give it an all around space to make the footer distinctive , and some font modifications

No it already assigned to @SaiKiranRebba

**Comment by SaiKiranRebba** [comment]
pr raised https://github.com/cggvuhh/My-online-meal.com/pull/25. Please check @Raunaksingh100 , @cggvuhh
