### ISSUE TITLE
Change the placeholder

### ISSUE THREAD

**Issue by cggvuhh** [cggvuhh/My-online-meal.com#8]
### Descption--
Change the placehoder to ""Enter your  phone number"" to ""Enter your number""
see in the screenshot for the better understanding

### screenshot-
![78](https://user-images.githubusercontent.com/68186540/94571413-96e27580-028d-11eb-9531-21033b8bf485.PNG)

**Comment by Raunaksingh100** [comment]
Can you assign me i will fixed
